#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="${1:-$ROOT_DIR/saas.env}"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Config file not found: $CONFIG_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$CONFIG_FILE"
set +a

required=(
  TOOL_PROJECT_ID
  REGION
  BQ_DATASET_ID
  CLOUD_RUN_SERVICE_NAME
  CLOUD_RUN_IMAGE
  WORKSPACE_CUSTOMER_ID
  RESOURCE_COLLECTION_SCHEDULE
  SCHEDULER_TIME_ZONE
  BQ_LOCATION
  TFSTATE_BUCKET
  TFSTATE_PREFIX
  TFSTATE_LOCATION
)

for key in "${required[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    echo "Missing required key in $CONFIG_FILE: $key" >&2
    exit 1
  fi
done

MANAGED_EFFECTIVE="${MANAGED_PROJECT_ID:-$TOOL_PROJECT_ID}"
if [[ -z "$MANAGED_EFFECTIVE" ]]; then
  MANAGED_EFFECTIVE="$TOOL_PROJECT_ID"
fi

cat > "$ROOT_DIR/environment.auto.tfvars" <<TFVARS
# Generated by scripts/sync-config.sh from $(basename "$CONFIG_FILE")
tool_project_id       = "$TOOL_PROJECT_ID"
managed_project_id    = "${MANAGED_PROJECT_ID:-}"
organization_id       = "${ORGANIZATION_ID:-}"
region                = "$REGION"
dataset_id            = "$BQ_DATASET_ID"
cloud_run_service_name = "$CLOUD_RUN_SERVICE_NAME"
cloud_run_image       = "$CLOUD_RUN_IMAGE"
gas_trigger_owner_email="${GAS_TRIGGER_OWNER_EMAIL}"
workspace_customer_id = "$WORKSPACE_CUSTOMER_ID"
resource_collection_schedule = "$RESOURCE_COLLECTION_SCHEDULE"
group_collection_schedule = "${GROUP_COLLECTION_SCHEDULE:-$RESOURCE_COLLECTION_SCHEDULE}"
scheduler_time_zone   = "$SCHEDULER_TIME_ZONE"
TFVARS

cat > "$ROOT_DIR/cloud-run/.env" <<ENV
# Generated by scripts/sync-config.sh from $(basename "$CONFIG_FILE")
BQ_PROJECT_ID=$TOOL_PROJECT_ID
BQ_DATASET_ID=$BQ_DATASET_ID
MGMT_TARGET_PROJECT_ID=$MANAGED_EFFECTIVE
MGMT_TARGET_ORGANIZATION_ID=${ORGANIZATION_ID:-}
WORKSPACE_CUSTOMER_ID=$WORKSPACE_CUSTOMER_ID
EXECUTOR_IDENTITY=iam-access-executor@$TOOL_PROJECT_ID.iam.gserviceaccount.com
GAS_INVOKER_EMAIL=${GAS_INVOKER_EMAIL:-}
ENV

cat > "$ROOT_DIR/apps-script/script-properties.json" <<JSON
{
  "BQ_PROJECT_ID": "$TOOL_PROJECT_ID",
  "BQ_DATASET_ID": "$BQ_DATASET_ID",
  "BQ_LOCATION": "$BQ_LOCATION",
  "CLOUD_RUN_EXECUTE_URL": "<set-after-terraform-output-cloud_run_url>",
  "GAS_INVOKER_EMAIL": "<set-from-gas-invoker-email>",
  "GEMINI_API_KEY": "${GEMINI_API_KEY:-}"
}
JSON

cat > "$ROOT_DIR/backend.hcl" <<HCL
# Generated by scripts/sync-config.sh from $(basename "$CONFIG_FILE")
bucket = "$TFSTATE_BUCKET"
prefix = "$TFSTATE_PREFIX"
HCL

mkdir -p "$ROOT_DIR/build/sql"
for sql in "$ROOT_DIR"/sql/*.sql; do
  name="$(basename "$sql")"
  sed "s|your_project.your_dataset|$TOOL_PROJECT_ID.$BQ_DATASET_ID|g" "$sql" > "$ROOT_DIR/build/sql/$name"
done

echo "Config synced from $CONFIG_FILE"
echo "- Generated: environment.auto.tfvars"
echo "- Generated: cloud-run/.env"
echo "- Generated: apps-script/script-properties.json"
echo "- Generated: backend.hcl"
echo "- Generated SQL: build/sql/*.sql"
