#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="${1:-$ROOT_DIR/saas.env}"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "Config file not found: $CONFIG_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$CONFIG_FILE"
set +a

# 1. 必須項目を最新のアーキテクチャに合わせて更新
required=(
  TOOL_PROJECT_ID
  REGION
  BQ_DATASET_ID
  CLOUD_RUN_SERVICE_NAME
  CLOUD_RUN_IMAGE
  WORKSPACE_CUSTOMER_ID
  RESOURCE_COLLECTION_SCHEDULE
  GROUP_COLLECTION_SCHEDULE
  IAM_POLICY_COLLECTION_SCHEDULE
  RECONCILIATION_SCHEDULE
  REVOKE_EXPIRED_PERMISSIONS_SCHEDULE
  IAM_BINDINGS_HISTORY_UPDATE_SCHEDULE
  SCHEDULER_TIME_ZONE
  BQ_LOCATION
  TFSTATE_BUCKET
  TFSTATE_PREFIX
  TFSTATE_LOCATION
)

for key in "${required[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    echo "Missing required key in $CONFIG_FILE: $key" >&2
    exit 1
  fi
done

MANAGED_EFFECTIVE="${MANAGED_PROJECT_ID:-$TOOL_PROJECT_ID}"
if [[ -z "$MANAGED_EFFECTIVE" ]]; then
  MANAGED_EFFECTIVE="$TOOL_PROJECT_ID"
fi

# VPC-SC設定のデフォルト値ハンドリング
ENABLE_VPC_SC="${enable_vpc_sc:-false}"
ACCESS_POLICY_NAME="${access_policy_name:-}"

# 2. Terraform用変数の出力 (すべての変数を網羅)
cat > "$ROOT_DIR/environment.auto.tfvars" <<TFVARS
# Generated by scripts/sync-config.sh from $(basename "$CONFIG_FILE")
tool_project_id                      = "$TOOL_PROJECT_ID"
managed_project_id                   = "${MANAGED_PROJECT_ID:-}"
organization_id                      = "${ORGANIZATION_ID:-}"
region                               = "$REGION"
dataset_id                           = "$BQ_DATASET_ID"
cloud_run_service_name               = "$CLOUD_RUN_SERVICE_NAME"
cloud_run_image                      = "$CLOUD_RUN_IMAGE"
gas_trigger_owner_email              = "${GAS_TRIGGER_OWNER_EMAIL:-}"
workspace_customer_id                = "$WORKSPACE_CUSTOMER_ID"
resource_collection_schedule         = "$RESOURCE_COLLECTION_SCHEDULE"
group_collection_schedule            = "$GROUP_COLLECTION_SCHEDULE"
iam_policy_collection_schedule       = "$IAM_POLICY_COLLECTION_SCHEDULE"
reconciliation_schedule              = "$RECONCILIATION_SCHEDULE"
revoke_expired_permissions_schedule  = "$REVOKE_EXPIRED_PERMISSIONS_SCHEDULE"
iam_bindings_history_update_schedule = "$IAM_BINDINGS_HISTORY_UPDATE_SCHEDULE"
scheduler_time_zone                  = "$SCHEDULER_TIME_ZONE"
alert_notification_email             = "${ALERT_NOTIFICATION_EMAIL:-}"
alert_notification_webhook_url       = "${ALERT_NOTIFICATION_WEBHOOK_URL:-}"
enable_vpc_sc                        = $ENABLE_VPC_SC
access_policy_name                   = "$ACCESS_POLICY_NAME"
TFVARS

# 3. Cloud Run / ローカルテスト用変数の出力
cat > "$ROOT_DIR/cloud-run/.env" <<ENV
# Generated by scripts/sync-config.sh from $(basename "$CONFIG_FILE")
BQ_PROJECT_ID=$TOOL_PROJECT_ID
BQ_DATASET_ID=$BQ_DATASET_ID
MGMT_TARGET_PROJECT_ID=$MANAGED_EFFECTIVE
MGMT_TARGET_ORGANIZATION_ID=${ORGANIZATION_ID:-}
WORKSPACE_CUSTOMER_ID=$WORKSPACE_CUSTOMER_ID
EXECUTOR_IDENTITY=iam-access-executor@$TOOL_PROJECT_ID.iam.gserviceaccount.com
GAS_INVOKER_EMAIL=iam-gas-invoker@$TOOL_PROJECT_ID.iam.gserviceaccount.com
SCHEDULER_INVOKER_EMAIL=iam-scheduler-invoker@$TOOL_PROJECT_ID.iam.gserviceaccount.com
ENV

# 4. GAS用プロパティの出力 (キー名をCode.gsの実装と一致させる)
cat > "$ROOT_DIR/apps-script/script-properties.json" <<JSON
{
  "BQ_PROJECT_ID": "$TOOL_PROJECT_ID",
  "BQ_DATASET_ID": "$BQ_DATASET_ID",
  "BQ_LOCATION": "$BQ_LOCATION",
  "CLOUD_RUN_EXECUTE_URL": "<set-after-terraform-output-cloud_run_url>",
  "GAS_INVOKER_SA_EMAIL": "iam-gas-invoker@$TOOL_PROJECT_ID.iam.gserviceaccount.com"
}
JSON

# Terraform バックエンド設定の出力
cat > "$ROOT_DIR/backend.hcl" <<HCL
# Generated by scripts/sync-config.sh from $(basename "$CONFIG_FILE")
bucket = "$TFSTATE_BUCKET"
prefix = "$TFSTATE_PREFIX"
HCL

# SQLファイルの置換と出力
mkdir -p "$ROOT_DIR/build/sql"
for sql in "$ROOT_DIR"/sql/*.sql; do
  if [[ -f "$sql" ]]; then
    name="$(basename "$sql")"
    sed "s|your_project.your_dataset|$TOOL_PROJECT_ID.$BQ_DATASET_ID|g" "$sql" > "$ROOT_DIR/build/sql/$name"
  fi
done

echo "✅ Config synced from $CONFIG_FILE"
echo "- Generated: environment.auto.tfvars"
echo "- Generated: cloud-run/.env"
echo "- Generated: apps-script/script-properties.json"
echo "- Generated: backend.hcl"
echo "- Generated SQL: build/sql/*.sql"
